#----------------------------------
# Defined for each environment
#----------------------------------
env.rms:
  server.port: 7003
  service.url:
    item: http://localhost:7002
    user: http://localhost:7004
  h2.user: sa
  h2.password:
  h2.script: classpath:init-rms.ddl

#----------------------------------
# Helidon Configurations
#----------------------------------
server:
  port: ${env.rms.server.port}
  access-log:
    format: "%t %h %r %s %b %D"

javax.sql.DataSource:
  rmsDataSource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    dataSource:
      url: jdbc:h2:mem:rms;INIT=RUNSCRIPT FROM '${env.rms.h2.script}'
      user: ${env.rms.h2.user}
      password: ${env.rms.h2.password:""}

web-api-item/mp-rest/url: ${env.rms.service.url.item}
web-api-user/mp-rest/url: ${env.rms.service.url.user}

#----------------------------------
# Applications Configurations
#----------------------------------
rms:
  app:
    name: ReservationService
  cdi:
    configuredCdi:
      register:
        - class: io.extact.msa.rms.platform.fw.external.PropagateLoginUserClientHeadersFactory
  persistence:
    apiType: jpa
    csv:
      type: temporary
      # following only used when type is "permanent" or ""temporary"
      permanent:
        directory: ./data
        fileName:
          reservation: reservation.csv
      temporary:
        fileName:
          reservation: temporary/reservationTemp.csv
  healthCheck:
    otherChecks:
      - io.extact.msa.rms.platform.core.health.ReadinessOfOutboundServersHealthCheck
      - io.extact.msa.rms.platform.core.health.DbReadinessCheck
    readinessOfOutboundServersHealthCheck.probe.url:
      - ${env.rms.service.url.item}
      - ${env.rms.service.url.user}
  openapi:
    title: レンタル品サービス公開API
  env:
    main.jar: msa-rms-service-reservation\.jar$
  debug:
    configdump:
      enable: true
      filter.pattern:
        - security
        - env.rms
        - server
