# Workflow - build, publish jar and image to GitHub Packages for this repository(msa-rms-service-reservation)
name: deploy-workflow

on:
  workflow_dispatch:
    inputs:
      skip-test:
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      skip-test:
        required: true
        type: boolean
      
jobs:
  execute:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job.yml@main
    with:
      repo: ${{ github.repository }}
      skip-test: ${{ inputs.skip-test }}
      with-image: true
      deploy-type: ecs
      ecs-taskname: reservation-service-task
      ecs-containername: reservation-service-container
      image-name: extact-io/msa-service-reservation
      ecs-servicename: reservation-service
    secrets: inherit
